### ISSUE TITLE
hostname command missing from image

### ISSUE THREAD

**Issue by jtriley** [tfhartmann/docker-puppetserver#1]
Causes issues when generating SSL certs for the puppet master.

Temporary fix is to run:

```
$ docker exec <container_name> yum install -y hostname
```

immediately after starting the container.

**Comment by tfhartmann** [comment]
@jtriley the hostname package _should_ be installed as a dependency to the Puppet Server install, although I had to add it to the puppetdb image...

https://github.com/tfhartmann/docker-puppetdb/blob/master/Dockerfile#L10

Is it missing on your version of tfhartmann/puppetserver ? 

``` Shell
[alaric@preator docker-puppetserver (issue1)]$ docker run -it --rm tfhartmann/puppetserver /bin/bash
[root@fc93e48f1e92 /]# hostname
fc93e48f1e92
[root@fc93e48f1e92 /]# which hostname
/usr/bin/hostname
[root@fc93e48f1e92 /]#
```

**Comment by tfhartmann** [comment]
@jtriley Ahh I see it now, looks like in the current autobild it's missing. Must have been installed on the base image. I'll update the Dockerfile and ensure it gets installed! Thanks for reporting this! 

``` Shell
[alaric@preator fia-io (gh-pages)]$ docker run -it --rm tfhartmann/puppetserver /bin/bash
[root@6466758f04bc /]# hostname
bash: hostname: command not found
[root@6466758f04bc /]# which hostname
/usr/bin/which: no hostname in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
[root@6466758f04bc /]#
```

**Comment by jtriley** [comment]
@tfhartmann Awesome, thanks for building/publishing docker-puppetserver!

**Comment by tfhartmann** [comment]
Dockerfile updated and pushed! you should be able to pull the updated image!

**Comment by tfhartmann** [comment]
@jtriley NP, I'm working on a suite of images to make deploying  Puppet Master infra a bit easier, so feel free to let me know if you see more stuff like this!
